steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'callback_manual/Dockerfile', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sudamerica/callback-manual:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sudamerica/callback-manual:latest'
options:
  logging: GCS_ONLY
