steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'api_execute/Dockerfile', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/sudamerica/api-execute:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sudamerica/api-execute:latest'
options:
  logging: GCS_ONLY
