steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://api-execute-552598955895.us-central1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyApbj8bRmPnmLj8tfniDmSO1P3cq-1C0MA'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=siavanza-d9722.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=siavanza-d9722'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=siavanza-d9722.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=218471513137'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:218471513137:web:5f1108a90c6a7876452910'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/sudamerica/sudamerica-admin:latest'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sudamerica/sudamerica-admin:latest'
timeout: '600s'
