// Diccionario de rubro (SSOT front) — Fase 0 multi-rubro.
// Espejo de shared/rubros/diccionario.py (backend). Mantener ambos en sync.
// Compat hacia atrás: RUBRO_DEFAULT = "restaurante"; un tenant sin `rubro` (o desconocido)
// resuelve a restaurante de forma fail-safe.

import type { Capacidad } from "./capacidades";
import { type Sector, type SectorConfig, getSectorConfig } from "./sector-config";

export type RubroKey =
  | "restaurante"
  | "peluqueria"
  | "barberia"
  | "ferreteria"
  | "veterinaria"
  | "carniceria"
  | "spa"
  | "clinica_dental"
  | "taller_mecanico"
  | "cafeteria"
  | "farmacia"
  | "pet_shop"
  | "lavado_autos"
  | "gimnasio"
  | "hotel"
  | "botilleria"
  | "clinica_estetica"
  | "tatuajes"
  | "fotografia"
  | "inmobiliaria"
  | "canchas"
  | "vivero"
  | "repuestos_auto"
  | "salon_unas"
  | "depilacion"
  | "podologia"
  | "kinesiologia"
  | "solarium"
  | "escuela_danza"
  | "escuela_musica"
  | "autoescuela"
  | "centro_idiomas"
  | "preuniversitario"
  | "escuela_natacion"
  | "centro_masajes"
  | "quiropraxia"
  | "estudio_yoga"
  | "estudio_pilates"
  | "consulta_medica_general"
  | "psicologia"
  | "laboratorio_clinico"
  | "centro_oftalmologico"
  | "nutricionista"
  | "vulcanizacion"
  | "lubricentro"
  | "desabolladura_pintura"
  | "peluqueria_canina"
  | "guarderia_mascotas"
  | "libreria_papeleria"
  | "jugueteria"
  | "tienda_ropa"
  | "zapateria"
  | "perfumeria"
  | "tienda_deportiva"
  | "tienda_celulares"
  | "tienda_computacion"
  | "electrodomesticos"
  | "muebleria"
  | "floreria"
  | "tienda_regalos"
  | "optica"
  | "tienda_bebes"
  | "cosmetica_belleza"
  | "bazar_hogar"
  | "pintureria"
  | "materiales_construccion"
  | "tienda_naturista"
  | "tienda_agricola"
  | "tienda_pesca_camping"
  | "tabaqueria_vapes"
  | "verduleria"
  | "fruteria"
  | "pescaderia"
  | "fiambreria"
  | "frutos_secos_granel"
  | "distribuidora_granos"
  | "pizzeria"
  | "sushi_delivery"
  | "heladeria"
  | "pasteleria"
  | "panaderia"
  | "jugueria"
  | "sandwicheria"
  | "empanadas"
  | "comida_rapida"
  | "chocolateria"
  | "food_truck"
  | "casino_almuerzos"
  | "productora_eventos"
  | "servicio_catering"
  | "dj_animacion"
  | "wedding_planner"
  | "arriendo_mobiliario"
  | "mudanzas_fletes"
  | "decoracion_eventos"
  | "arriendo_maquinaria"
  | "agencia_marketing"
  | "estudio_diseno"
  | "agencia_viajes"
  | "hostal"
  | "cabanias";

// Claves canónicas de las primitivas de negocio (internas, agnósticas de rubro).
export type Primitiva =
  | "catalogo"
  | "item"
  | "categoria"
  | "orden"
  | "recurso"
  | "agenda"
  | "parte"
  | "transaccion"
  | "variante"
  | "equipo"
  | "metricas"
  | "ingesta";

export const PRIMITIVAS: readonly Primitiva[] = [
  "catalogo",
  "item",
  "categoria",
  "orden",
  "recurso",
  "agenda",
  "parte",
  "transaccion",
  "variante",
  "equipo",
  "metricas",
  "ingesta",
] as const;

export interface RubroDef {
  key: RubroKey;
  nombre: string;
  emoji: string;
  sector: Sector; // enlaza con SECTOR_CONFIG (KPIs/benchmarks)
  labels: Record<Primitiva, string>;
  categoriasSemilla: readonly string[];
  /** F6: etiqueta de la sub-entidad del cliente (Mascota/Vehículo/…); label ⟹ capacidad expedientes. */
  subEntidadLabel?: string;
  /**
   * Categorización (ERP+CRM): subconjunto curado de CAPACIDADES en orden CAP_ORDER
   * (ver capacidades.ts). Requerido: los 100 rubros lo definen.
   */
  capacidades: readonly Capacidad[];
  // Flags de DATO sin capacidad de navegación (Etapa B — reemplazo de `modulos`):
  // gatean prompt/roles/UI como modos de operación, no vistas del sidebar.
  /** Recurso físico reservable (Mesa/Silla/Bahía…). Default false. */
  recurso?: boolean;
  /** Grupos de modificadores en el catálogo. Default true. */
  variantes?: boolean;
  /** Precio por peso/medida (kg, m², hora). Default false. */
  precioMedida?: boolean;
}

export const RUBRO_DEFAULT: RubroKey = "restaurante";

export const RUBROS: Record<RubroKey, RubroDef> = {
  restaurante: {
    key: "restaurante",
    nombre: "Restaurante",
    emoji: "🍽️",
    sector: "gastronomia",
    labels: {
      catalogo: "Carta",
      item: "Plato",
      categoria: "Sección de Carta",
      orden: "Comanda",
      recurso: "Mesa",
      agenda: "Reserva",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modificador",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    // Módulos operativos actuales ON → comportamiento idéntico a hoy. "inventario"
    // (stock por ítem) OFF: los insumos del restaurante van por Suministro/Receta,
    // flujo incondicional no gateado por flag (F3) → UI byte-idéntica.
    recurso: true,
    categoriasSemilla: ["Entradas", "Platos de Fondo", "Bebidas", "Postres"],
    capacidades: ["catalogo", "agenda", "pedidos", "pagos", "delivery", "mesas"],
  },
  peluqueria: {
    key: "peluqueria",
    nombre: "Peluquería / Barbería",
    emoji: "💇",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Servicio",
      orden: "Atención",
      recurso: "Silla",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    // Servicio-con-cita: agenda + recurso; sin cocina/delivery/stock.
    recurso: true,
    categoriasSemilla: [
      "Cortes",
      "Color",
      "Peinados",
      "Tratamientos Capilares",
      "Barbería",
      "Manicure",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "fidelizacion", "campanas"],
  },
  barberia: {
    key: "barberia",
    nombre: "Barbería",
    emoji: "💈",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Servicio",
      orden: "Atención",
      recurso: "Sillón",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Barberos",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    // Grooming masculino servicio-con-cita: agenda + recurso (sillón); sin cocina/delivery/stock.
    recurso: true,
    categoriasSemilla: [
      "Cortes de Caballero",
      "Afeitado Clásico",
      "Arreglo de Barba",
      "Corte + Barba",
      "Corte Niño",
      "Diseño y Perfilado",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "fidelizacion", "campanas"],
  },
  ferreteria: {
    key: "ferreteria",
    nombre: "Ferretería / Minimarket",
    emoji: "🔧",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Artículo",
      categoria: "Pasillo",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Variante",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    // Retail-con-stock: inventario + despacho; sin agenda/recurso/cocina.
    categoriasSemilla: [
      "Herramientas",
      "Fijaciones",
      "Eléctrico",
      "Plomería",
      "Pinturas",
      "Construcción",
      "Jardín",
    ],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "facturacion",
    ],
  },
  veterinaria: {
    key: "veterinaria",
    nombre: "Veterinaria",
    emoji: "🐾",
    sector: "mascotas",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Servicio",
      orden: "Atención",
      recurso: "Sala",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    // Servicio-con-cita + sub-entidad (F6): la mascota es el sujeto de la atención.
    recurso: true,
    categoriasSemilla: ["Consultas", "Vacunas", "Cirugías", "Estética", "Exámenes"],
    subEntidadLabel: "Mascota",
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "inventario",
      "compras",
      "expedientes",
      "campanas",
      "consentimientos",
    ],
  },
  carniceria: {
    key: "carniceria",
    nombre: "Carnicería",
    emoji: "🥩",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Variante",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    // Retail por peso (F7 M5): primer usuario de precio_medida ($/kg) + stock + despacho.
    precioMedida: true,
    categoriasSemilla: ["Vacuno", "Cerdo", "Pollo", "Cecinas", "Preparados"],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  // ── F7 M8 Ola 1: rubros data-only (sin módulos nuevos) ────────────────────
  spa: {
    key: "spa",
    nombre: "Spa",
    emoji: "💆",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Tratamiento",
      categoria: "Tipo de Tratamiento",
      orden: "Sesión",
      recurso: "Sala",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Masajes", "Faciales", "Hidroterapia", "Aromaterapia", "Reflexología"],
    capacidades: ["catalogo", "agenda", "pagos", "suscripciones", "fidelizacion", "campanas"],
  },
  clinica_dental: {
    key: "clinica_dental",
    nombre: "Clínica Dental",
    emoji: "🦷",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Procedimiento",
      categoria: "Tipo de Servicio",
      orden: "Atención",
      recurso: "Consultorio",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Limpiezas", "Empastes", "Extracciones", "Ortodoncia", "Estética"],
    subEntidadLabel: "Paciente",
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "expedientes",
      "facturacion",
      "campanas",
      "consentimientos",
    ],
  },
  taller_mecanico: {
    key: "taller_mecanico",
    nombre: "Taller Mecánico",
    emoji: "🛠️",
    sector: "automotriz",
    labels: {
      catalogo: "Servicios",
      item: "Reparación",
      categoria: "Sistema",
      orden: "Orden de Trabajo",
      recurso: "Bahía",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Motor", "Frenos", "Suspensión", "Electricidad", "Transmisión"],
    subEntidadLabel: "Vehículo",
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pedidos",
      "pagos",
      "soporte",
      "inventario",
      "compras",
      "expedientes",
      "facturacion",
      "terreno",
    ],
  },
  cafeteria: {
    key: "cafeteria",
    nombre: "Cafetería",
    emoji: "☕",
    sector: "gastronomia",
    labels: {
      catalogo: "Menú",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Reserva",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: ["Café", "Desayunos", "Sándwiches", "Pasteles", "Bebidas Frías"],
    capacidades: ["catalogo", "pedidos", "pagos", "delivery", "fidelizacion", "campanas"],
  },
  farmacia: {
    key: "farmacia",
    nombre: "Farmacia",
    emoji: "💊",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Presentación",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: ["Medicamentos", "Dermocosmética", "Suplementos", "Higiene", "Vitaminas"],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  pet_shop: {
    key: "pet_shop",
    nombre: "Pet Shop",
    emoji: "🐕",
    sector: "mascotas",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Presentación",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: ["Alimentos", "Accesorios", "Juguetes", "Camas", "Higiene"],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  lavado_autos: {
    key: "lavado_autos",
    nombre: "Lavado de Autos",
    emoji: "🚗",
    sector: "automotriz",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Lavado",
      orden: "Atención",
      recurso: "Puesto",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Lavado Básico", "Lavado Premium", "Interior", "Detallado", "Encerado"],
    capacidades: ["catalogo", "agenda", "pagos", "fidelizacion", "campanas"],
  },
  gimnasio: {
    key: "gimnasio",
    nombre: "Gimnasio / Clases",
    emoji: "💪",
    sector: "educacion",
    labels: {
      catalogo: "Clases",
      item: "Clase",
      categoria: "Tipo de Actividad",
      orden: "Inscripción",
      recurso: "Sala",
      agenda: "Horario",
      parte: "Alumno",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Clases",
    },
    recurso: true,
    categoriasSemilla: ["Yoga", "Pilates", "Spinning", "Crossfit", "Zumba", "Funcional"],
    capacidades: ["catalogo", "agenda", "pagos", "suscripciones", "cursos", "campanas"],
  },
  hotel: {
    key: "hotel",
    nombre: "Hotel / Alojamiento",
    emoji: "🏨",
    sector: "turismo",
    labels: {
      catalogo: "Habitaciones",
      item: "Tipo de Habitación",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Habitación",
      agenda: "Reserva",
      parte: "Huésped",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Habitaciones",
    },
    recurso: true,
    categoriasSemilla: ["Individual", "Doble", "Matrimonial", "Suite", "Familiar"],
    capacidades: ["catalogo", "agenda", "pagos", "facturacion", "campanas"],
  },
  botilleria: {
    key: "botilleria",
    nombre: "Botillería",
    emoji: "🍷",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: ["Vinos", "Cervezas", "Licores", "Bebidas", "Snacks"],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  // ── F7 M8 Ola 2: rubros data-only (cierra los arquetipos viables) ─────────
  clinica_estetica: {
    key: "clinica_estetica",
    nombre: "Clínica Estética",
    emoji: "✨",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Procedimiento",
      categoria: "Tipo de Tratamiento",
      orden: "Sesión",
      recurso: "Box",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Facial", "Corporal", "Depilación Láser", "Inyectables", "Peelings"],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "expedientes",
      "fidelizacion",
      "campanas",
      "consentimientos",
    ],
  },
  tatuajes: {
    key: "tatuajes",
    nombre: "Estudio de Tatuajes",
    emoji: "🖋️",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Tatuaje",
      categoria: "Estilo",
      orden: "Sesión",
      recurso: "Estación",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Tribal", "Realista", "Minimalista", "Geométrico", "Tradicional"],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "expedientes",
      "campanas",
      "consentimientos",
    ],
  },
  fotografia: {
    key: "fotografia",
    nombre: "Estudio Fotográfico",
    emoji: "📸",
    sector: "otro",
    labels: {
      catalogo: "Paquetes",
      item: "Paquete",
      categoria: "Tipo de Sesión",
      orden: "Sesión",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Paquetes",
    },
    categoriasSemilla: ["Bodas", "Eventos", "Retratos", "Producto", "Book"],
    capacidades: ["catalogo", "agenda", "cotizador", "pagos", "campanas"],
  },
  inmobiliaria: {
    key: "inmobiliaria",
    nombre: "Inmobiliaria",
    emoji: "🏠",
    sector: "inmobiliario",
    labels: {
      catalogo: "Propiedades",
      item: "Propiedad",
      categoria: "Tipo de Propiedad",
      orden: "Visita",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Variante",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Propiedades",
    },
    variantes: false,
    categoriasSemilla: ["Casas", "Departamentos", "Locales", "Terrenos", "Oficinas"],
    subEntidadLabel: "Propiedad",
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "soporte",
      "expedientes",
      "contratos",
      "arriendos",
      "facturacion",
      "campanas",
      "terreno",
      "consentimientos",
    ],
  },
  canchas: {
    key: "canchas",
    nombre: "Canchas Deportivas",
    emoji: "⚽",
    sector: "otro",
    labels: {
      catalogo: "Canchas",
      item: "Cancha",
      categoria: "Deporte",
      orden: "Reserva",
      recurso: "Cancha",
      agenda: "Horario",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Canchas",
    },
    recurso: true,
    categoriasSemilla: ["Fútbol", "Tenis", "Pádel", "Básquetbol", "Vóleibol"],
    capacidades: ["catalogo", "agenda", "pagos", "fidelizacion", "campanas"],
  },
  vivero: {
    key: "vivero",
    nombre: "Vivero",
    emoji: "🌱",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Planta",
      categoria: "Tipo de Planta",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Plantas de Interior",
      "Plantas de Exterior",
      "Árboles",
      "Suculentas",
      "Maceteros",
    ],
    capacidades: ["catalogo", "pedidos", "pagos", "delivery", "inventario", "compras", "campanas"],
  },
  repuestos_auto: {
    key: "repuestos_auto",
    nombre: "Repuestos de Auto",
    emoji: "🔩",
    sector: "automotriz",
    labels: {
      catalogo: "Catálogo",
      item: "Repuesto",
      categoria: "Sistema",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modelo",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: ["Motor", "Suspensión", "Frenos", "Eléctrico", "Accesorios"],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "soporte",
      "inventario",
      "compras",
      "facturacion",
    ],
  },
  salon_unas: {
    key: "salon_unas",
    nombre: "Salón de Uñas",
    emoji: "💅",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Manicure",
      orden: "Atención",
      recurso: "Puesto",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Manicure Tradicional",
      "Pedicure",
      "Uñas Acrílicas",
      "Esmaltado Permanente",
      "Kapping",
      "Nail Art",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "fidelizacion", "campanas"],
  },
  depilacion: {
    key: "depilacion",
    nombre: "Centro de Depilación",
    emoji: "🪒",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Zona de Depilación",
      orden: "Sesión",
      recurso: "Box",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Depilación Láser",
      "Depilación con Cera",
      "Axilas",
      "Piernas Completas",
      "Zona Bikini",
      "Rostro",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "pagos",
      "expedientes",
      "fidelizacion",
      "campanas",
      "consentimientos",
    ],
  },
  podologia: {
    key: "podologia",
    nombre: "Centro de Podología",
    emoji: "🦶",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Tratamiento",
      orden: "Atención",
      recurso: "Box",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Podología Clínica",
      "Uña Encarnada",
      "Tratamiento de Callos",
      "Reflexología Podal",
      "Onicomicosis",
      "Pie Diabético",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "expedientes", "consentimientos"],
  },
  kinesiologia: {
    key: "kinesiologia",
    nombre: "Centro de Kinesiología",
    emoji: "🧑‍⚕️",
    sector: "otro",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Terapia",
      orden: "Sesión",
      recurso: "Box",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Kinesiología Deportiva",
      "Rehabilitación Traumatológica",
      "Terapia Manual",
      "Electroterapia",
      "Masoterapia",
      "Kinesiología Respiratoria",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "expedientes", "facturacion", "consentimientos"],
  },
  solarium: {
    key: "solarium",
    nombre: "Centro de Solárium",
    emoji: "🌞",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Bronceado",
      orden: "Sesión",
      recurso: "Cabina",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Bronceado UV",
      "Cama Solar",
      "Bronceado de Pie",
      "Autobronceado",
      "Sesión Express",
      "Bronceado Progresivo",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "pagos",
      "expedientes",
      "fidelizacion",
      "campanas",
      "consentimientos",
    ],
  },
  escuela_danza: {
    key: "escuela_danza",
    nombre: "Escuela de Danza",
    emoji: "💃",
    sector: "educacion",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Estilo de Danza",
      orden: "Clase",
      recurso: "Sala",
      agenda: "Horario",
      parte: "Alumno",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Ballet", "Jazz", "Danza Contemporánea", "Flamenco", "Salsa", "Hip Hop"],
    capacidades: ["catalogo", "agenda", "pagos", "suscripciones", "cursos", "campanas"],
  },
  escuela_musica: {
    key: "escuela_musica",
    nombre: "Escuela de Música",
    emoji: "🎵",
    sector: "educacion",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Instrumento",
      orden: "Clase",
      recurso: "Sala",
      agenda: "Horario",
      parte: "Alumno",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Guitarra", "Piano", "Batería", "Canto", "Violín", "Bajo Eléctrico"],
    capacidades: ["catalogo", "agenda", "pagos", "suscripciones", "cursos", "campanas"],
  },
  autoescuela: {
    key: "autoescuela",
    nombre: "Autoescuela",
    emoji: "🚗",
    sector: "automotriz",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Licencia",
      orden: "Clase",
      recurso: "Sala",
      agenda: "Cita",
      parte: "Alumno",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Licencia Clase B",
      "Licencia Clase A",
      "Clases Prácticas",
      "Clases Teóricas",
      "Preparación Examen",
      "Reforzamiento de Manejo",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "cursos", "campanas"],
  },
  centro_idiomas: {
    key: "centro_idiomas",
    nombre: "Centro de Idiomas",
    emoji: "🗣️",
    sector: "educacion",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Idioma",
      orden: "Clase",
      recurso: "Sala",
      agenda: "Horario",
      parte: "Alumno",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: ["Inglés", "Portugués", "Francés", "Alemán", "Italiano", "Chino Mandarín"],
    capacidades: [
      "catalogo",
      "agenda",
      "pagos",
      "suscripciones",
      "cursos",
      "facturacion",
      "campanas",
    ],
  },
  preuniversitario: {
    key: "preuniversitario",
    nombre: "Preuniversitario",
    emoji: "📚",
    sector: "educacion",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Asignatura",
      orden: "Clase",
      recurso: "Sala",
      agenda: "Horario",
      parte: "Alumno",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Matemática M1",
      "Competencia Lectora",
      "Ciencias",
      "Historia",
      "Ensayo PAES",
      "Reforzamiento Individual",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "suscripciones", "cursos", "campanas"],
  },
  escuela_natacion: {
    key: "escuela_natacion",
    nombre: "Escuela de Natación",
    emoji: "🏊",
    sector: "educacion",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Nivel de Natación",
      orden: "Clase",
      recurso: "Andarivel",
      agenda: "Horario",
      parte: "Alumno",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Natación Bebés",
      "Natación Infantil",
      "Natación Adultos",
      "Perfeccionamiento",
      "Aquagym",
      "Hidroterapia",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "suscripciones", "cursos", "campanas"],
  },
  centro_masajes: {
    key: "centro_masajes",
    nombre: "Centro de Masajes",
    emoji: "💆",
    sector: "salud_estetica",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Masaje",
      orden: "Sesión",
      recurso: "Box",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Masaje Relajante",
      "Descontracturante",
      "Piedras Calientes",
      "Drenaje Linfático",
      "Masaje Deportivo",
      "Reflexología",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "fidelizacion", "campanas"],
  },
  quiropraxia: {
    key: "quiropraxia",
    nombre: "Centro de Quiropraxia",
    emoji: "🦴",
    sector: "otro",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Ajuste",
      orden: "Sesión",
      recurso: "Box",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Ajuste Quiropráctico",
      "Ajuste Cervical",
      "Ajuste Lumbar",
      "Descompresión Vertebral",
      "Evaluación Postural",
      "Terapia de Mantención",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "expedientes", "consentimientos"],
  },
  estudio_yoga: {
    key: "estudio_yoga",
    nombre: "Estudio de Yoga",
    emoji: "🧘",
    sector: "educacion",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Estilo de Yoga",
      orden: "Clase",
      recurso: "Sala",
      agenda: "Horario",
      parte: "Alumno",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Hatha Yoga",
      "Vinyasa",
      "Yin Yoga",
      "Ashtanga",
      "Yoga Restaurativo",
      "Meditación Guiada",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "suscripciones", "cursos", "campanas"],
  },
  estudio_pilates: {
    key: "estudio_pilates",
    nombre: "Estudio de Pilates",
    emoji: "🤸",
    sector: "otro",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de Pilates",
      orden: "Clase",
      recurso: "Sala",
      agenda: "Horario",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Nivel",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Lista de Servicios",
    },
    recurso: true,
    categoriasSemilla: [
      "Pilates Reformer",
      "Pilates Mat",
      "Pilates Terapéutico",
      "Pilates Prenatal",
      "Pilates Wall",
      "Barre",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "suscripciones", "cursos", "campanas"],
  },
  consulta_medica_general: {
    key: "consulta_medica_general",
    nombre: "Consulta Médica General",
    emoji: "🩺",
    sector: "salud_estetica",
    labels: {
      catalogo: "Prestaciones",
      item: "Prestación",
      categoria: "Especialidad",
      orden: "Atención",
      recurso: "Box",
      agenda: "Hora médica",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modalidad",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Medicina general",
      "Control de salud",
      "Certificados médicos",
      "Chequeo preventivo",
      "Consulta a domicilio",
      "Telemedicina",
    ],
    subEntidadLabel: "Paciente",
    capacidades: ["catalogo", "agenda", "pagos", "expedientes", "facturacion", "consentimientos"],
  },
  psicologia: {
    key: "psicologia",
    nombre: "Consulta de Psicología",
    emoji: "🧠",
    sector: "salud_estetica",
    labels: {
      catalogo: "Terapias",
      item: "Sesión",
      categoria: "Área de atención",
      orden: "Atención",
      recurso: "Consultorio",
      agenda: "Hora de terapia",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modalidad",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Terapia individual",
      "Terapia de pareja",
      "Terapia infantil",
      "Evaluación psicológica",
      "Psicología online",
      "Terapia familiar",
    ],
    subEntidadLabel: "Paciente",
    capacidades: ["catalogo", "agenda", "pagos", "expedientes", "facturacion", "consentimientos"],
  },
  laboratorio_clinico: {
    key: "laboratorio_clinico",
    nombre: "Laboratorio Clínico",
    emoji: "🧪",
    sector: "salud_estetica",
    labels: {
      catalogo: "Exámenes",
      item: "Examen",
      categoria: "Tipo de examen",
      orden: "Toma de muestra",
      recurso: "Box de toma de muestra",
      agenda: "Hora de examen",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Perfil",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Hemograma",
      "Perfil bioquímico",
      "Perfil lipídico",
      "Examen de orina",
      "Pruebas tiroideas",
      "Test de embarazo",
    ],
    subEntidadLabel: "Paciente",
    capacidades: [
      "catalogo",
      "agenda",
      "pedidos",
      "pagos",
      "expedientes",
      "facturacion",
      "consentimientos",
    ],
  },
  centro_oftalmologico: {
    key: "centro_oftalmologico",
    nombre: "Centro Oftalmológico",
    emoji: "👁️",
    sector: "salud_estetica",
    labels: {
      catalogo: "Prestaciones",
      item: "Prestación",
      categoria: "Especialidad",
      orden: "Atención",
      recurso: "Box",
      agenda: "Hora oftalmológica",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modalidad",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Control de visión",
      "Examen de vista",
      "Fondo de ojo",
      "Presión ocular",
      "Adaptación de lentes",
      "Cirugía refractiva",
    ],
    subEntidadLabel: "Paciente",
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "expedientes",
      "facturacion",
      "consentimientos",
    ],
  },
  nutricionista: {
    key: "nutricionista",
    nombre: "Consulta de Nutrición",
    emoji: "🥗",
    sector: "salud_estetica",
    labels: {
      catalogo: "Prestaciones",
      item: "Consulta",
      categoria: "Área nutricional",
      orden: "Atención",
      recurso: "Consultorio",
      agenda: "Hora nutricional",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Plan",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Control de peso",
      "Nutrición deportiva",
      "Nutrición infantil",
      "Diabetes y metabolismo",
      "Nutrición vegetariana",
      "Evaluación antropométrica",
    ],
    subEntidadLabel: "Paciente",
    capacidades: ["catalogo", "agenda", "pagos", "expedientes", "facturacion"],
  },
  vulcanizacion: {
    key: "vulcanizacion",
    nombre: "Vulcanización y Gomería",
    emoji: "🛞",
    sector: "automotriz",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de servicio",
      orden: "Orden de trabajo",
      recurso: "Bahía",
      agenda: "Hora de atención",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Medida de neumático",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Parche de neumático",
      "Alineación",
      "Balanceo",
      "Rotación de neumáticos",
      "Cambio de neumático",
      "Reparación de llanta",
    ],
    subEntidadLabel: "Vehículo",
    capacidades: [
      "catalogo",
      "agenda",
      "pedidos",
      "pagos",
      "inventario",
      "compras",
      "expedientes",
      "terreno",
    ],
  },
  lubricentro: {
    key: "lubricentro",
    nombre: "Lubricentro y Cambio de Aceite",
    emoji: "🛢️",
    sector: "automotriz",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de mantención",
      orden: "Orden de trabajo",
      recurso: "Bahía",
      agenda: "Hora de mantención",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tipo de aceite",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Cambio de aceite",
      "Cambio de filtros",
      "Revisión de niveles",
      "Lubricación general",
      "Cambio de refrigerante",
      "Mantención preventiva",
    ],
    subEntidadLabel: "Vehículo",
    capacidades: ["catalogo", "agenda", "pedidos", "pagos", "inventario", "compras", "expedientes"],
  },
  desabolladura_pintura: {
    key: "desabolladura_pintura",
    nombre: "Desabolladura y Pintura",
    emoji: "🎨",
    sector: "automotriz",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de reparación",
      orden: "Orden de trabajo",
      recurso: "Bahía de pintura",
      agenda: "Hora de recepción",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Nivel de daño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Desabolladura",
      "Pintura completa",
      "Pulido y encerado",
      "Reparación de rayones",
      "Cambio de parachoques",
      "Pintura de tapabarros",
    ],
    subEntidadLabel: "Vehículo",
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pedidos",
      "pagos",
      "soporte",
      "inventario",
      "compras",
      "expedientes",
      "facturacion",
    ],
  },
  peluqueria_canina: {
    key: "peluqueria_canina",
    nombre: "Peluquería Canina",
    emoji: "🐩",
    sector: "mascotas",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de servicio",
      orden: "Orden de atención",
      recurso: "Sala de grooming",
      agenda: "Hora de atención",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño de mascota",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Baño e higiene",
      "Corte de pelo",
      "Corte de uñas",
      "Deslanado",
      "Limpieza de oídos",
      "Baño medicado",
    ],
    subEntidadLabel: "Mascota",
    capacidades: ["catalogo", "agenda", "pagos", "expedientes", "fidelizacion", "campanas"],
  },
  guarderia_mascotas: {
    key: "guarderia_mascotas",
    nombre: "Guardería de Mascotas",
    emoji: "🐾",
    sector: "mascotas",
    labels: {
      catalogo: "Servicios",
      item: "Servicio",
      categoria: "Tipo de estadía",
      orden: "Reserva",
      recurso: "Sala",
      agenda: "Reserva de estadía",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño de mascota",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importación",
    },
    recurso: true,
    categoriasSemilla: [
      "Guardería diurna",
      "Alojamiento nocturno",
      "Paseo canino",
      "Estadía fin de semana",
      "Adiestramiento básico",
      "Día de juegos",
    ],
    subEntidadLabel: "Mascota",
    capacidades: [
      "catalogo",
      "agenda",
      "pagos",
      "suscripciones",
      "expedientes",
      "campanas",
      "consentimientos",
    ],
  },
  libreria_papeleria: {
    key: "libreria_papeleria",
    nombre: "Librería y Papelería",
    emoji: "📚",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Artículo",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Cuadernos",
      "Lápices y escritura",
      "Artículos de oficina",
      "Libros",
      "Mochilas y estuches",
      "Papeles y cartulinas",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "facturacion",
      "fidelizacion",
      "campanas",
    ],
  },
  jugueteria: {
    key: "jugueteria",
    nombre: "Juguetería",
    emoji: "🧸",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Juguete",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modelo",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Juegos de mesa",
      "Muñecas",
      "Autos y pistas",
      "Peluches",
      "Bloques y armables",
      "Juguetes de aire libre",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  tienda_ropa: {
    key: "tienda_ropa",
    nombre: "Tienda de Ropa",
    emoji: "👕",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Prenda",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Talla",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Mujer",
      "Hombre",
      "Niños",
      "Accesorios",
      "Ropa interior",
      "Abrigos y chaquetas",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  zapateria: {
    key: "zapateria",
    nombre: "Zapatería",
    emoji: "👟",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Par",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Talla",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Zapatillas",
      "Zapatos formales",
      "Botas",
      "Sandalias",
      "Calzado infantil",
      "Deportivo",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  perfumeria: {
    key: "perfumeria",
    nombre: "Perfumería",
    emoji: "🌸",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Perfume",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Perfumes mujer",
      "Perfumes hombre",
      "Cremas y lociones",
      "Sets de regalo",
      "Desodorantes",
      "Cuidado facial",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  tienda_deportiva: {
    key: "tienda_deportiva",
    nombre: "Tienda Deportiva",
    emoji: "⚽",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Artículo",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Talla",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Ropa deportiva",
      "Zapatillas",
      "Fútbol",
      "Fitness",
      "Camping y outdoor",
      "Accesorios",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  tienda_celulares: {
    key: "tienda_celulares",
    nombre: "Tienda de Celulares",
    emoji: "📱",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Celular",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modelo",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Smartphones",
      "Fundas y carcasas",
      "Cargadores",
      "Audífonos",
      "Accesorios",
      "Repuestos",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "soporte",
      "inventario",
      "compras",
      "facturacion",
      "campanas",
    ],
  },
  tienda_computacion: {
    key: "tienda_computacion",
    nombre: "Tienda de Computación",
    emoji: "💻",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modelo",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Notebooks",
      "Componentes",
      "Periféricos",
      "Almacenamiento",
      "Redes",
      "Gaming",
    ],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "soporte",
      "inventario",
      "compras",
      "facturacion",
      "campanas",
    ],
  },
  electrodomesticos: {
    key: "electrodomesticos",
    nombre: "Electrodomésticos",
    emoji: "🔌",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Electrodoméstico",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modelo",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Refrigeración",
      "Cocina",
      "Lavado",
      "Climatización",
      "Pequeños electrodomésticos",
      "Audio y video",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "soporte",
      "inventario",
      "compras",
      "facturacion",
      "campanas",
    ],
  },
  muebleria: {
    key: "muebleria",
    nombre: "Mueblería",
    emoji: "🛋️",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Mueble",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modelo",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: ["Living", "Dormitorio", "Comedor", "Oficina", "Terraza", "Colchones"],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "soporte",
      "inventario",
      "compras",
      "facturacion",
      "campanas",
    ],
  },
  floreria: {
    key: "floreria",
    nombre: "Florería",
    emoji: "💐",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Arreglo",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Ramos",
      "Arreglos florales",
      "Plantas",
      "Coronas",
      "Flores por tallo",
      "Regalos",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  tienda_regalos: {
    key: "tienda_regalos",
    nombre: "Tienda de Regalos",
    emoji: "🎁",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Regalo",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Variante",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Peluches",
      "Tazas y mugs",
      "Decoración",
      "Tarjetas",
      "Velas y aromas",
      "Sets de regalo",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  optica: {
    key: "optica",
    nombre: "Óptica",
    emoji: "👓",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Lente",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modelo",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Lentes ópticos",
      "Lentes de sol",
      "Marcos",
      "Lentes de contacto",
      "Accesorios",
      "Líquidos",
    ],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "campanas",
    ],
  },
  tienda_bebes: {
    key: "tienda_bebes",
    nombre: "Tienda para Bebés",
    emoji: "👶",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Artículo",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Talla",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Ropa de bebé",
      "Coches y sillas",
      "Alimentación",
      "Pañales",
      "Juguetes",
      "Cuna y dormitorio",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  cosmetica_belleza: {
    key: "cosmetica_belleza",
    nombre: "Cosmética y Belleza",
    emoji: "💄",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Presentación",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Maquillaje",
      "Cuidado facial",
      "Cuidado capilar",
      "Uñas",
      "Cuidado corporal",
      "Accesorios",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  bazar_hogar: {
    key: "bazar_hogar",
    nombre: "Bazar y Hogar",
    emoji: "🏠",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Artículo",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Variante",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: ["Cocina", "Organización", "Baño", "Decoración", "Menaje", "Textil hogar"],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  pintureria: {
    key: "pintureria",
    nombre: "Pinturería",
    emoji: "🎨",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Pinturas",
      "Esmaltes",
      "Barnices",
      "Brochas y rodillos",
      "Diluyentes",
      "Accesorios",
    ],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "facturacion",
    ],
  },
  materiales_construccion: {
    key: "materiales_construccion",
    nombre: "Materiales de Construcción",
    emoji: "🧱",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Material",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Cemento y áridos",
      "Fierro y acero",
      "Maderas",
      "Techumbre",
      "Aislación",
      "Fijaciones",
    ],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "facturacion",
    ],
  },
  tienda_naturista: {
    key: "tienda_naturista",
    nombre: "Tienda Naturista",
    emoji: "🌿",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Suplementos",
      "Vitaminas",
      "Hierbas",
      "Alimentos saludables",
      "Aceites esenciales",
      "Cosmética natural",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  tienda_agricola: {
    key: "tienda_agricola",
    nombre: "Tienda Agrícola",
    emoji: "🌾",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Semillas",
      "Fertilizantes",
      "Agroquímicos",
      "Riego",
      "Herramientas",
      "Alimento animal",
    ],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "facturacion",
    ],
  },
  tienda_pesca_camping: {
    key: "tienda_pesca_camping",
    nombre: "Pesca y Camping",
    emoji: "🎣",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Artículo",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modelo",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Cañas y carretes",
      "Señuelos",
      "Carpas",
      "Sacos de dormir",
      "Cocinas y camping",
      "Bolsos y mochilas",
    ],
    capacidades: ["catalogo", "pedidos", "pagos", "delivery", "inventario", "compras", "campanas"],
  },
  tabaqueria_vapes: {
    key: "tabaqueria_vapes",
    nombre: "Tabaquería y Vapes",
    emoji: "🚬",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Categoría",
      orden: "Pedido",
      recurso: "Recurso",
      agenda: "Cita",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Cigarrillos",
      "Vapes y pods",
      "Líquidos",
      "Tabaco de armar",
      "Accesorios",
      "Encendedores",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
    ],
  },
  verduleria: {
    key: "verduleria",
    nombre: "Verdulería",
    emoji: "🥬",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Local",
      agenda: "Horario de reparto",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Presentación",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Carga de productos",
    },
    precioMedida: true,
    categoriasSemilla: [
      "Verduras de hoja",
      "Tubérculos y papas",
      "Tomates y ajíes",
      "Aliños y hierbas",
      "Zapallos y choclos",
      "Legumbres frescas",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  fruteria: {
    key: "fruteria",
    nombre: "Frutería",
    emoji: "🍓",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Puesto",
      agenda: "Horario de reparto",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Calibre",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Carga de productos",
    },
    precioMedida: true,
    categoriasSemilla: [
      "Fruta de estación",
      "Cítricos",
      "Frutas tropicales",
      "Berries",
      "Frutas de carozo",
      "Paltas y plátanos",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  pescaderia: {
    key: "pescaderia",
    nombre: "Pescadería y Marisquería",
    emoji: "🐟",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Mesón",
      agenda: "Horario de reparto",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Corte",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Carga de productos",
    },
    precioMedida: true,
    categoriasSemilla: [
      "Pescado fresco",
      "Mariscos",
      "Moluscos",
      "Crustáceos",
      "Congelados",
      "Ahumados y conservas",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  fiambreria: {
    key: "fiambreria",
    nombre: "Fiambrería y Quesería",
    emoji: "🧀",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Mostrador",
      agenda: "Horario de reparto",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Grosor de corte",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Carga de productos",
    },
    precioMedida: true,
    categoriasSemilla: [
      "Jamones",
      "Quesos",
      "Cecinas",
      "Embutidos",
      "Fiambres",
      "Encurtidos y aceitunas",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  frutos_secos_granel: {
    key: "frutos_secos_granel",
    nombre: "Frutos Secos a Granel",
    emoji: "🥜",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Dispensador",
      agenda: "Horario de reparto",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Carga de productos",
    },
    precioMedida: true,
    categoriasSemilla: [
      "Frutos secos",
      "Semillas",
      "Frutas deshidratadas",
      "Cereales y granolas",
      "Confites a granel",
      "Snacks a granel",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "fidelizacion",
      "campanas",
    ],
  },
  distribuidora_granos: {
    key: "distribuidora_granos",
    nombre: "Distribuidora de Granos y Legumbres",
    emoji: "🌾",
    sector: "retail",
    labels: {
      catalogo: "Catálogo",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Bodega",
      agenda: "Horario de despacho",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato de saco",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Carga de productos",
    },
    precioMedida: true,
    categoriasSemilla: [
      "Legumbres",
      "Arroces",
      "Harinas",
      "Cereales",
      "Semillas",
      "Azúcares y sal",
    ],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "inventario",
      "compras",
      "facturacion",
    ],
  },
  pizzeria: {
    key: "pizzeria",
    nombre: "Pizzería",
    emoji: "🍕",
    sector: "gastronomia",
    labels: {
      catalogo: "Carta",
      item: "Pizza",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Pizzas tradicionales",
      "Pizzas especiales",
      "Empanadas de pizza",
      "Bebidas",
      "Acompañamientos",
      "Postres",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  sushi_delivery: {
    key: "sushi_delivery",
    nombre: "Sushi / Comida Japonesa",
    emoji: "🍣",
    sector: "gastronomia",
    labels: {
      catalogo: "Carta",
      item: "Roll",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Rolls California",
      "Rolls fritos",
      "Handrolls",
      "Combinaciones",
      "Nigiri y sashimi",
      "Bebidas",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  heladeria: {
    key: "heladeria",
    nombre: "Heladería",
    emoji: "🍦",
    sector: "gastronomia",
    labels: {
      catalogo: "Menú",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Helados de agua",
      "Helados de crema",
      "Copas y sundaes",
      "Malteados",
      "Paletas",
      "Postres helados",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  pasteleria: {
    key: "pasteleria",
    nombre: "Pastelería",
    emoji: "🎂",
    sector: "gastronomia",
    labels: {
      catalogo: "Carta",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Tortas",
      "Kuchenes",
      "Pie y tartaletas",
      "Pasteles individuales",
      "Dulces chilenos",
      "Sin azúcar",
    ],
    capacidades: [
      "catalogo",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  panaderia: {
    key: "panaderia",
    nombre: "Panadería",
    emoji: "🥖",
    sector: "gastronomia",
    labels: {
      catalogo: "Menú",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Pan amasado",
      "Marraquetas y hallullas",
      "Pan especial",
      "Pasteles",
      "Empanadas",
      "Fiambres",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  jugueria: {
    key: "jugueria",
    nombre: "Juguería",
    emoji: "🥤",
    sector: "gastronomia",
    labels: {
      catalogo: "Menú",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Jugos naturales",
      "Batidos",
      "Smoothies",
      "Bowls de fruta",
      "Aguas saborizadas",
      "Ensaladas de fruta",
    ],
    capacidades: ["catalogo", "pedidos", "pagos", "delivery", "fidelizacion", "campanas"],
  },
  sandwicheria: {
    key: "sandwicheria",
    nombre: "Sandwichería",
    emoji: "🥪",
    sector: "gastronomia",
    labels: {
      catalogo: "Carta",
      item: "Sándwich",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Churrascos",
      "Completos",
      "Mechada",
      "Barros luco",
      "Vegetarianos",
      "Bebidas",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  empanadas: {
    key: "empanadas",
    nombre: "Empanadas",
    emoji: "🥟",
    sector: "gastronomia",
    labels: {
      catalogo: "Menú",
      item: "Empanada",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: ["Horno", "Fritas", "De mariscos", "Vegetarianas", "Dulces", "Bebidas"],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  comida_rapida: {
    key: "comida_rapida",
    nombre: "Comida Rápida",
    emoji: "🍔",
    sector: "gastronomia",
    labels: {
      catalogo: "Menú",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Hamburguesas",
      "Papas fritas",
      "Hot dogs",
      "Combos",
      "Pollo frito",
      "Bebidas",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  chocolateria: {
    key: "chocolateria",
    nombre: "Chocolatería",
    emoji: "🍫",
    sector: "gastronomia",
    labels: {
      catalogo: "Carta",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Bombones",
      "Barras de chocolate",
      "Cajas de regalo",
      "Trufas",
      "Chocolate caliente",
      "Sin azúcar",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  food_truck: {
    key: "food_truck",
    nombre: "Food Truck",
    emoji: "🚚",
    sector: "gastronomia",
    labels: {
      catalogo: "Menú",
      item: "Producto",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Street food",
      "Tacos",
      "Burgers gourmet",
      "Papas rústicas",
      "Bebidas artesanales",
      "Postres",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "fidelizacion",
      "campanas",
    ],
  },
  casino_almuerzos: {
    key: "casino_almuerzos",
    nombre: "Casino / Almuerzos",
    emoji: "🍱",
    sector: "gastronomia",
    labels: {
      catalogo: "Menú",
      item: "Plato",
      categoria: "Sección",
      orden: "Pedido",
      recurso: "Repartidor",
      agenda: "Agenda",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Opción",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Menú",
    },
    categoriasSemilla: [
      "Menú del día",
      "Platos caseros",
      "Ensaladas",
      "Sopas",
      "Postres",
      "Colaciones",
    ],
    capacidades: [
      "catalogo",
      "pedidos",
      "pagos",
      "delivery",
      "suscripciones",
      "compras",
      "produccion",
      "facturacion",
      "fidelizacion",
      "campanas",
    ],
  },
  productora_eventos: {
    key: "productora_eventos",
    nombre: "Productora de Eventos",
    emoji: "🎪",
    sector: "otro",
    labels: {
      catalogo: "Paquetes de Producción",
      item: "Servicio",
      categoria: "Tipo de Evento",
      orden: "Cotización",
      recurso: "Recurso",
      agenda: "Agenda de Eventos",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Modalidad",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Paquetes",
    },
    categoriasSemilla: [
      "Matrimonios",
      "Eventos Corporativos",
      "Lanzamientos de Marca",
      "Fiestas Privadas",
      "Conciertos",
      "Ferias y Expos",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "proyectos",
      "contratos",
      "facturacion",
      "campanas",
      "terreno",
    ],
  },
  servicio_catering: {
    key: "servicio_catering",
    nombre: "Servicio de Catering",
    emoji: "🍽️",
    sector: "otro",
    labels: {
      catalogo: "Catálogo de Menús",
      item: "Plato",
      categoria: "Tipo de Menú",
      orden: "Pedido de Catering",
      recurso: "Recurso",
      agenda: "Agenda de Servicios",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Formato",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Cóctel",
      "Coffee Break",
      "Almuerzo Ejecutivo",
      "Banquete",
      "Buffet",
      "Servicio a Domicilio",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pedidos",
      "pagos",
      "delivery",
      "compras",
      "produccion",
      "facturacion",
      "terreno",
    ],
  },
  dj_animacion: {
    key: "dj_animacion",
    nombre: "DJ y Animación",
    emoji: "🎧",
    sector: "otro",
    labels: {
      catalogo: "Catálogo de Shows",
      item: "Show",
      categoria: "Tipo de Animación",
      orden: "Reserva",
      recurso: "Recurso",
      agenda: "Agenda de Fechas",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Duración",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Paquetes",
    },
    categoriasSemilla: [
      "DJ Matrimonios",
      "Animación Infantil",
      "Karaoke",
      "Hora Loca",
      "Fiestas de Empresa",
      "Cumpleaños",
    ],
    capacidades: ["catalogo", "agenda", "cotizador", "pagos", "campanas"],
  },
  wedding_planner: {
    key: "wedding_planner",
    nombre: "Wedding Planner",
    emoji: "💍",
    sector: "otro",
    labels: {
      catalogo: "Paquetes de Boda",
      item: "Paquete",
      categoria: "Tipo de Boda",
      orden: "Contrato",
      recurso: "Recurso",
      agenda: "Agenda de Bodas",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Nivel de Servicio",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Paquetes",
    },
    categoriasSemilla: [
      "Full Planning",
      "Coordinación del Día",
      "Boda Íntima",
      "Boda Destino",
      "Ceremonia Civil",
      "Renovación de Votos",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "proyectos",
      "contratos",
      "campanas",
      "terreno",
    ],
  },
  arriendo_mobiliario: {
    key: "arriendo_mobiliario",
    nombre: "Arriendo de Mobiliario para Eventos",
    emoji: "🪑",
    sector: "otro",
    labels: {
      catalogo: "Catálogo de Mobiliario",
      item: "Artículo",
      categoria: "Categoría",
      orden: "Arriendo",
      recurso: "Recurso",
      agenda: "Agenda de Arriendos",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Color",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: ["Sillas", "Mesas", "Toldos", "Vajilla", "Mantelería", "Living", "Tarimas"],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "inventario",
      "compras",
      "contratos",
      "arriendos",
      "facturacion",
      "terreno",
    ],
  },
  mudanzas_fletes: {
    key: "mudanzas_fletes",
    nombre: "Mudanzas y Fletes",
    emoji: "🚚",
    sector: "otro",
    labels: {
      catalogo: "Servicios de Mudanza",
      item: "Servicio",
      categoria: "Tipo de Traslado",
      orden: "Orden de Servicio",
      recurso: "Recurso",
      agenda: "Agenda de Fletes",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Tamaño de Camión",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Mudanza Casa",
      "Mudanza Oficina",
      "Flete Express",
      "Traslado de Pianos",
      "Bodegaje",
      "Embalaje",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pedidos",
      "pagos",
      "contratos",
      "arriendos",
      "facturacion",
      "terreno",
    ],
  },
  decoracion_eventos: {
    key: "decoracion_eventos",
    nombre: "Decoración de Eventos",
    emoji: "🎈",
    sector: "otro",
    labels: {
      catalogo: "Servicios de Decoración",
      item: "Servicio",
      categoria: "Estilo",
      orden: "Cotización",
      recurso: "Recurso",
      agenda: "Agenda de Montajes",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Paleta de Color",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Paquetes",
    },
    categoriasSemilla: [
      "Globos",
      "Arcos",
      "Ambientación",
      "Centros de Mesa",
      "Backdrops",
      "Iluminación",
      "Flores",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "proyectos",
      "contratos",
      "arriendos",
      "campanas",
      "terreno",
    ],
  },
  arriendo_maquinaria: {
    key: "arriendo_maquinaria",
    nombre: "Arriendo de Maquinaria",
    emoji: "🏗️",
    sector: "b2b",
    labels: {
      catalogo: "Catálogo de Maquinaria",
      item: "Máquina",
      categoria: "Tipo de Maquinaria",
      orden: "Arriendo",
      recurso: "Recurso",
      agenda: "Agenda de Arriendos",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Capacidad",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Retroexcavadoras",
      "Generadores",
      "Andamios",
      "Compresores",
      "Grúas Horquilla",
      "Placas Compactadoras",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "soporte",
      "inventario",
      "compras",
      "contratos",
      "arriendos",
      "facturacion",
      "terreno",
    ],
  },
  agencia_marketing: {
    key: "agencia_marketing",
    nombre: "Agencia de Marketing",
    emoji: "📈",
    sector: "b2b",
    labels: {
      catalogo: "Catálogo de Servicios",
      item: "Servicio",
      categoria: "Área",
      orden: "Propuesta",
      recurso: "Recurso",
      agenda: "Agenda de Reuniones",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Plan",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Redes Sociales",
      "SEO",
      "Google Ads",
      "Diseño de Marca",
      "Email Marketing",
      "Producción de Contenido",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "suscripciones",
      "proyectos",
      "contratos",
      "facturacion",
    ],
  },
  estudio_diseno: {
    key: "estudio_diseno",
    nombre: "Estudio de Diseño",
    emoji: "🎨",
    sector: "b2b",
    labels: {
      catalogo: "Servicios de Diseño",
      item: "Servicio",
      categoria: "Especialidad",
      orden: "Proyecto",
      recurso: "Recurso",
      agenda: "Agenda de Proyectos",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Alcance",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Catálogo",
    },
    categoriasSemilla: [
      "Identidad Corporativa",
      "Diseño Web",
      "Packaging",
      "Ilustración",
      "Diseño Editorial",
      "Motion Graphics",
    ],
    capacidades: [
      "catalogo",
      "agenda",
      "cotizador",
      "pagos",
      "proyectos",
      "contratos",
      "facturacion",
    ],
  },
  agencia_viajes: {
    key: "agencia_viajes",
    nombre: "Agencia de Viajes",
    emoji: "✈️",
    sector: "turismo",
    labels: {
      catalogo: "Paquetes Turísticos",
      item: "Paquete",
      categoria: "Destino",
      orden: "Reserva",
      recurso: "Recurso",
      agenda: "Agenda de Viajes",
      parte: "Cliente",
      transaccion: "Venta",
      variante: "Temporada",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar Paquetes",
    },
    categoriasSemilla: [
      "Playas del Caribe",
      "Sur de Chile",
      "Cruceros",
      "Europa",
      "Torres del Paine",
      "San Pedro de Atacama",
      "Viajes de Egresados",
    ],
    capacidades: ["catalogo", "agenda", "cotizador", "pagos", "campanas"],
  },
  hostal: {
    key: "hostal",
    nombre: "Hostal",
    emoji: "🛏️",
    sector: "turismo",
    labels: {
      catalogo: "Habitaciones",
      item: "Tipo de habitación",
      categoria: "Categoría",
      orden: "Reserva",
      recurso: "Habitación",
      agenda: "Reserva",
      parte: "Huésped",
      transaccion: "Venta",
      variante: "Variante",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar tarifario",
    },
    recurso: true,
    categoriasSemilla: [
      "Cama en dormitorio compartido",
      "Habitación privada individual",
      "Habitación privada doble",
      "Habitación familiar",
      "Habitación matrimonial",
      "Suite",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "campanas"],
  },
  cabanias: {
    key: "cabanias",
    nombre: "Cabañas",
    emoji: "🏡",
    sector: "turismo",
    labels: {
      catalogo: "Cabañas",
      item: "Tipo de cabaña",
      categoria: "Categoría",
      orden: "Reserva",
      recurso: "Cabaña",
      agenda: "Reserva",
      parte: "Huésped",
      transaccion: "Venta",
      variante: "Variante",
      equipo: "Equipo",
      metricas: "Métricas",
      ingesta: "Importar tarifas",
    },
    recurso: true,
    categoriasSemilla: [
      "Cabaña para 2 personas",
      "Cabaña para 4 personas",
      "Cabaña para 6 personas",
      "Cabaña familiar",
      "Cabaña con tinaja",
      "Domo",
      "Tiny house",
    ],
    capacidades: ["catalogo", "agenda", "pagos", "campanas"],
  },
};

function isRubroKey(value: string): value is RubroKey {
  return value in RUBROS;
}

/** Resuelve la clave de rubro desde el `config` del tenant; fail-safe a restaurante.
 * Acepta el `config` genérico del tenant (`Record<string, unknown>`) y estrecha con seguridad. */
export function resolveRubro(config: Record<string, unknown> | null | undefined): RubroKey {
  const key = config?.rubro;
  if (typeof key === "string" && isRubroKey(key)) {
    return key;
  }
  return RUBRO_DEFAULT;
}

/** Definición del rubro; fail-safe a restaurante si es null/desconocido. */
export function getRubroDef(key: string | null | undefined): RubroDef {
  if (typeof key === "string" && isRubroKey(key)) {
    return RUBROS[key];
  }
  return RUBROS[RUBRO_DEFAULT];
}

/** ¿El rubro tiene activa esta capacidad? */
export function tieneCapacidad(key: RubroKey, capacidad: Capacidad): boolean {
  return RUBROS[key].capacidades.includes(capacidad);
}

/** Pluraliza en español una etiqueta singular (Silla → Sillas, Cita → Citas). */
export function plural(word: string): string {
  if (!word) return word;
  const last = word.charAt(word.length - 1).toLowerCase();
  return "aeiouáéíóú".includes(last) ? `${word}s` : `${word}es`;
}

/** KPIs/benchmarks LATAM del rubro (reutiliza el mapa de sector-config). */
export function rubroSectorConfig(key: RubroKey): SectorConfig {
  return getSectorConfig(RUBROS[key].sector);
}

/** Opciones para el selector de rubro del onboarding. */
export const RUBRO_OPTIONS: readonly { value: RubroKey; label: string; emoji: string }[] = (
  Object.keys(RUBROS) as RubroKey[]
).map((key) => ({ value: key, label: RUBROS[key].nombre, emoji: RUBROS[key].emoji }));
